[package]
name = "torch-sys"
version = "0.4.0"
authors = ["Laurent Mazare <lmazare@gmail.com>"]
edition = "2018"
build = "build.rs"
links = "tch"

description = "Low-level FFI bindings for the PyTorch C++ api (libtorch)."
repository = "https://github.com/LaurentMazare/tch-rs"
keywords = ["pytorch", "ffi", "deep-learning", "machine-learning"]
categories = ["external-ffi-bindings", "science"]
license = "MIT/Apache-2.0"

[dependencies]
libc = "0.2.0"

[build-dependencies]
anyhow = "1.0"
cc = "1.0"
curl = "0.4.9"
zip = "0.5"
normpath="0.3.0"
verbatim="0.1.1"
cfg-if="1.0.0"

[features]
doc-only = []

[package.metadata.docs.rs]
features = [ "doc-only" ]
